name: Build React App and Serve with Nginx

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'infra/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'infra/**'
    branches:
      - master


jobs:
  build-internal:
    secrets: inherit
    uses: ./.github/workflows/parent-build.yaml
    with:
      backend-url: "https://cars-backend.at-dias.cloud"
      docker-tag: "internal"
      docker-repository: cars-frontend

  build-external:
    secrets: inherit
    uses: ./.github/workflows/parent-build.yaml
    with:
      backend-url: "https://cars-backend-external.at-dias.cloud"
      docker-tag: "external"
      docker-repository: cars-frontend
