name: Reusable Build

on:
  workflow_call:
    inputs:
      backend-url:
        required: true
        type: string
      docker-tag:
        required: true
        type: string
      docker-repository:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your Node.js version

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        env:
          REACT_APP_BACKEND_URL: ${{ inputs.backend-url }}
          NODE_ENV: "production"
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.docker-repository }}:${{ inputs.docker-tag }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag ${{ inputs.docker-repository }}:${{ inputs.docker-tag }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker-repository }}:${{ inputs.docker-tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker-repository }}:${{ inputs.docker-tag }}
